type User @table {
  id: String! @default(expr: "auth.uid")
}

type Post @table {
  imageUrl: String!
  caption: String
  createdAt: Timestamp! @default(expr: "request.time")
  location: String
  author: User!
}
